name: Build and Push Containerd Image to ACR

on: workflow_dispatch

env:
  ACR_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  image_name: oapi-conatinerd
  tag: latest

jobs:
  containerd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ env.ACR_REGISTRY }}/${{ env.image_name }}:${{ env.tag }}
          outputs: type=oci,dest=/tmp/image.tar
      
      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name ${{ env.ACR_REGISTRY }}/${{ env.image_name }}:${{ env.tag }} --digests --all-platforms /tmp/image.tar
          echo ${{ env.ACR_REGISTRY }}/${{ env.image_name }}:${{ env.tag }}
      
      - name: Push image with containerd
        run: |
          sudo ctr i push --user "${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}" ${{ env.ACR_REGISTRY }}/${{ env.image_name }}:${{ env.tag }}
